baseurl = "https://www.weber-inter.net"
title = "Otherland"
description = "Where dreams start living..."
theme = "m10c"
paginate = 10

[author]
  name = "Otherland"

[taxonomies]
  category = "categories"

[menu]
[[menu.main]]
  identifier = 'Home'
  name = 'Home'
  url = '/'
  weight = -110

[params]
  description = "Where dreams start living..."

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/mweberkl"
