baseurl = "https://www.weber-inter.net"
title = "Otherland"
description = "Where dreams start living..."
theme = "m10c"
paginate = 10

[author]
  name = "Otherland"

[taxonomies]
  category = "categories"

[params]
  highlight = "solarized_dark"
  tagline = "Where dreams start living..."

  twitter = "https://twitter.com/mweberkl"
